const fs = require('fs')

fs.writeFileSync('src/components/Navbar.tsx', [
  "import type { Translations } from '../i18n/en'",
  "",
  "interface NavbarProps {",
  "  t: Translations",
  "}",
  "",
  "export default function Navbar({ t }: NavbarProps) {",
  "  return (",
  "    <nav className=\"fixed top-0 left-0 right-0 z-50 bg-white border-b border-slate-200\" style={{ boxShadow: '0 1px 3px 0 rgba(0,0,0,0.08)' }}>",
  "      <div className=\"max-w-6xl mx-auto px-6 h-16 flex items-center justify-between\">",
  "        <div className=\"flex items-center gap-2\">",
  "          <div className=\"w-8 h-8 rounded-lg bg-blue-600 flex items-center justify-center\">",
  "            <svg width=\"18\" height=\"18\" viewBox=\"0 0 18 18\" fill=\"none\">",
  "              <rect x=\"2\" y=\"2\" width=\"6\" height=\"6\" rx=\"1.5\" fill=\"white\"/>",
  "              <rect x=\"10\" y=\"2\" width=\"6\" height=\"6\" rx=\"1.5\" fill=\"white\" opacity=\"0.7\"/>",
  "              <rect x=\"2\" y=\"10\" width=\"6\" height=\"6\" rx=\"1.5\" fill=\"white\" opacity=\"0.7\"/>",
  "              <rect x=\"10\" y=\"10\" width=\"6\" height=\"6\" rx=\"1.5\" fill=\"white\" opacity=\"0.4\"/>",
  "            </svg>",
  "          </div>",
  "          <span className=\"font-semibold text-slate-900 text-lg tracking-tight\">PLANIVO</span>",
  "        </div>",
  "        <div className=\"flex items-center gap-4\">",
  "          <a href=\"https://app.planivoapp.com/login\" className=\"text-sm font-medium text-slate-600 hover:text-slate-900 transition-colors\">",
  "            {t.nav.login}",
  "          </a>",
  "          <a href=\"https://app.planivoapp.com/register\" className=\"text-sm font-medium bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors\">",
  "            {t.nav.cta}",
  "          </a>",
  "        </div>",
  "      </div>",
  "    </nav>",
  "  )",
  "}"
].join('\n'))

fs.writeFileSync('src/components/sections/Hero.tsx', [
  "import type { Translations } from '../../i18n/en'",
  "",
  "interface HeroProps {",
  "  t: Translations",
  "}",
  "",
  "export default function Hero({ t }: HeroProps) {",
  "  return (",
  "    <section className=\"pt-32 pb-20 px-6\" style={{ background: 'linear-gradient(180deg, #eef0f4 0%, #ffffff 100%)' }}>",
  "      <div className=\"max-w-4xl mx-auto text-center\">",
  "        <div className=\"inline-flex items-center gap-2 bg-blue-50 border border-blue-100 text-blue-700 text-sm font-medium px-4 py-2 rounded-full mb-8\">",
  "          <span className=\"w-2 h-2 rounded-full bg-blue-500 inline-block\"></span>",
  "          {t.hero.badge}",
  "        </div>",
  "        <h1 className=\"text-5xl font-bold text-slate-900 leading-tight mb-6 tracking-tight\">",
  "          {t.hero.title.split('\\n').map((line, i) => (",
  "            <span key={i}>",
  "              {i === 0 ? line : <><br /><span className=\"text-blue-600\">{line}</span></>}",
  "            </span>",
  "          ))}",
  "        </h1>",
  "        <p className=\"text-xl text-slate-500 max-w-2xl mx-auto mb-10 leading-relaxed\">",
  "          {t.hero.subtitle}",
  "        </p>",
  "        <div className=\"flex items-center justify-center gap-4 flex-wrap\">",
  "          <a href=\"https://app.planivoapp.com/register\" className=\"bg-blue-600 text-white font-semibold px-8 py-4 rounded-xl hover:bg-blue-700 transition-colors text-base\" style={{ boxShadow: '0 4px 14px 0 rgba(37,99,235,0.35)' }}>",
  "            {t.hero.cta_primary}",
  "          </a>",
  "          <a href=\"#how-it-works\" className=\"text-slate-700 font-medium px-8 py-4 rounded-xl border border-slate-200 hover:border-slate-300 hover:bg-slate-50 transition-colors text-base bg-white\">",
  "            {t.hero.cta_secondary}",
  "          </a>",
  "        </div>",
  "      </div>",
  "      <div className=\"max-w-5xl mx-auto mt-16\">",
  "        <div className=\"rounded-2xl border border-slate-200 overflow-hidden\" style={{ boxShadow: '0 20px 60px 0 rgba(0,0,0,0.12)' }}>",
  "          <div className=\"bg-slate-100 px-4 py-3 flex items-center gap-2 border-b border-slate-200\">",
  "            <div className=\"w-3 h-3 rounded-full bg-red-400\"></div>",
  "            <div className=\"w-3 h-3 rounded-full bg-yellow-400\"></div>",
  "            <div className=\"w-3 h-3 rounded-full bg-green-400\"></div>",
  "            <div className=\"flex-1 mx-4 bg-white rounded text-xs text-slate-400 px-3 py-1 text-center\">",
  "              app.planivoapp.com",
  "            </div>",
  "          </div>",
  "          <div className=\"bg-slate-50 h-80 flex items-center justify-center\">",
  "            <div className=\"text-center\">",
  "              <div className=\"w-16 h-16 rounded-2xl bg-blue-600 flex items-center justify-center mx-auto mb-4\" style={{ boxShadow: '0 8px 24px rgba(37,99,235,0.3)' }}>",
  "                <svg width=\"32\" height=\"32\" viewBox=\"0 0 32 32\" fill=\"none\">",
  "                  <rect x=\"4\" y=\"4\" width=\"11\" height=\"11\" rx=\"2.5\" fill=\"white\"/>",
  "                  <rect x=\"17\" y=\"4\" width=\"11\" height=\"11\" rx=\"2.5\" fill=\"white\" opacity=\"0.7\"/>",
  "                  <rect x=\"4\" y=\"17\" width=\"11\" height=\"11\" rx=\"2.5\" fill=\"white\" opacity=\"0.7\"/>",
  "                  <rect x=\"17\" y=\"17\" width=\"11\" height=\"11\" rx=\"2.5\" fill=\"white\" opacity=\"0.4\"/>",
  "                </svg>",
  "              </div>",
  "              <p className=\"text-slate-400 text-sm\">App screenshot placeholder</p>",
  "              <p className=\"text-slate-300 text-xs mt-1\">Sostituire con screenshot reale</p>",
  "            </div>",
  "          </div>",
  "        </div>",
  "      </div>",
  "    </section>",
  "  )",
  "}"
].join('\n'))

fs.writeFileSync('src/components/sections/CTAFinal.tsx', [
  "import type { Translations } from '../../i18n/en'",
  "",
  "interface CTAFinalProps {",
  "  t: Translations",
  "}",
  "",
  "export default function CTAFinal({ t }: CTAFinalProps) {",
  "  return (",
  "    <section className=\"py-24 px-6 bg-white\">",
  "      <div className=\"max-w-3xl mx-auto text-center\">",
  "        <div className=\"rounded-3xl bg-blue-600 px-12 py-16\" style={{ boxShadow: '0 20px 60px 0 rgba(37,99,235,0.3)' }}>",
  "          <h2 className=\"text-3xl font-bold text-white mb-4\">",
  "            {t.cta_final.title}",
  "          </h2>",
  "          <p className=\"text-blue-200 text-lg mb-8\">",
  "            {t.cta_final.subtitle}",
  "          </p>",
  "          <a href=\"https://app.planivoapp.com/register\" className=\"inline-block bg-white text-blue-600 font-semibold px-8 py-4 rounded-xl hover:bg-blue-50 transition-colors text-base\" style={{ boxShadow: '0 4px 14px 0 rgba(0,0,0,0.1)' }}>",
  "            {t.cta_final.cta}",
  "          </a>",
  "        </div>",
  "      </div>",
  "    </section>",
  "  )",
  "}"
].join('\n'))

fs.writeFileSync('src/components/sections/Pricing.tsx', [
  "import { useState } from 'react'",
  "import type { Translations } from '../../i18n/en'",
  "",
  "interface PricingProps {",
  "  t: Translations",
  "}",
  "",
  "export default function Pricing({ t }: PricingProps) {",
  "  const [annual, setAnnual] = useState(false)",
  "",
  "  return (",
  "    <section className=\"py-24 px-6\" style={{ background: '#eef0f4' }}>",
  "      <div className=\"max-w-6xl mx-auto\">",
  "        <div className=\"text-center mb-12\">",
  "          <h2 className=\"text-3xl font-bold text-slate-900 mb-4\">",
  "            {t.pricing.title}",
  "          </h2>",
  "          <p className=\"text-lg text-slate-500 mb-8\">",
  "            {t.pricing.subtitle}",
  "          </p>",
  "          <div className=\"inline-flex items-center gap-3 bg-white border border-slate-200 rounded-xl p-1\">",
  "            <button onClick={() => setAnnual(false)} className={`px-5 py-2 rounded-lg text-sm font-medium transition-colors ${!annual ? 'bg-blue-600 text-white' : 'text-slate-500 hover:text-slate-700'}`}>",
  "              {t.pricing.monthly}",
  "            </button>",
  "            <button onClick={() => setAnnual(true)} className={`px-5 py-2 rounded-lg text-sm font-medium transition-colors flex items-center gap-2 ${annual ? 'bg-blue-600 text-white' : 'text-slate-500 hover:text-slate-700'}`}>",
  "              {t.pricing.annual}",
  "              <span className={`text-xs px-2 py-0.5 rounded-full font-semibold ${annual ? 'bg-blue-500 text-white' : 'bg-green-100 text-green-700'}`}>",
  "                {t.pricing.save}",
  "              </span>",
  "            </button>",
  "          </div>",
  "        </div>",
  "        <div className=\"grid grid-cols-4 gap-4\">",
  "          {t.pricing.plans.map((plan, i) => (",
  "            <div key={i} className={`rounded-2xl p-6 flex flex-col ${plan.popular ? 'bg-blue-600 text-white' : 'bg-white border border-slate-100'}`} style={{ boxShadow: plan.popular ? '0 8px 32px 0 rgba(37,99,235,0.3)' : '0 2px 8px 0 rgba(0,0,0,0.05)' }}>",
  "              <div className=\"mb-6\">",
  "                {plan.popular && (",
  "                  <span className=\"inline-block text-xs font-semibold bg-blue-500 text-white px-3 py-1 rounded-full mb-3\">",
  "                    {t.pricing.popular}",
  "                  </span>",
  "                )}",
  "                <h3 className={`text-lg font-bold mb-1 ${plan.popular ? 'text-white' : 'text-slate-900'}`}>",
  "                  {plan.name}",
  "                </h3>",
  "                <p className={`text-sm mb-4 ${plan.popular ? 'text-blue-200' : 'text-slate-400'}`}>",
  "                  {plan.description}",
  "                </p>",
  "                <div className={`text-3xl font-bold mb-1 ${plan.popular ? 'text-white' : 'text-slate-900'}`}>",
  "                  {annual ? plan.price_annual : plan.price_monthly}",
  "                  <span className={`text-sm font-normal ml-1 ${plan.popular ? 'text-blue-200' : 'text-slate-400'}`}>/mo</span>",
  "                </div>",
  "                <p className={`text-xs ${plan.popular ? 'text-blue-200' : 'text-slate-400'}`}>",
  "                  {plan.users}",
  "                </p>",
  "              </div>",
  "              <ul className=\"flex-1 space-y-2 mb-6\">",
  "                {plan.features.map((feature, j) => (",
  "                  <li key={j} className=\"flex items-center gap-2 text-sm\">",
  "                    <svg width=\"16\" height=\"16\" viewBox=\"0 0 16 16\" fill=\"none\">",
  "                      <circle cx=\"8\" cy=\"8\" r=\"7\" fill={plan.popular ? 'rgba(255,255,255,0.2)' : '#eff6ff'}/>",
  "                      <path d=\"M5 8l2 2 4-4\" stroke={plan.popular ? 'white' : '#2563eb'} strokeWidth=\"1.5\" strokeLinecap=\"round\" strokeLinejoin=\"round\"/>",
  "                    </svg>",
  "                    <span className={plan.popular ? 'text-blue-100' : 'text-slate-600'}>{feature}</span>",
  "                  </li>",
  "                ))}",
  "              </ul>",
  "              <a href=\"https://app.planivoapp.com/register\" className={`block text-center py-3 rounded-xl text-sm font-semibold transition-colors ${plan.popular ? 'bg-white text-blue-600 hover:bg-blue-50' : 'bg-blue-600 text-white hover:bg-blue-700'}`}>",
  "                {t.pricing.cta}",
  "              </a>",
  "            </div>",
  "          ))}",
  "        </div>",
  "      </div>",
  "    </section>",
  "  )",
  "}"
].join('\n'))